name: Hudl Playwright
'on':
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: '${{ secrets.USER_EMAIL }}'
      USER_PASSWORD: '${{ secrets.USER_PASSWORD }}'
      WRONG_EMAIL: '${{ secrets.WRONG_EMAIL }}'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Scan & audit for secrets
        if: github.ref != 'refs/heads/master'
        run: |
          pip install detect-secrets
          detect-secrets scan > .secrets.baseline

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Playwright Browsers
        id: playwright-version
        run: >-
          echo "PLAYWRIGHT_VERSION=$(node -p
          "require('./package-lock.json').packages['node_modules/@playwright/test'].version")"
          >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: '${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}'
      - run: npm ci
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Audit npm dependencies for vulnerabilities
        if: github.ref != 'refs/heads/master'
        run: npm audit --audit-level=high

      - name: Run Linting
        if: github.ref != 'refs/heads/master'
        run: npm run lint

      - name: Run Playwright tests
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        run: 'npm run functional:ci'
      
      - name: Upload Artifacts - Playwright Reports
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
      - name: Upload Playwright report
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        run: |
          if [ -d "playwright-report" ]; then
            echo "Uploading Playwright report..."
            gh run upload-artifact playwright-report --name playwright-report
          else
            echo "No report folder found, skipping upload."
          fi
       
          retention-days: 4
