name: Hudl Playwright Project - CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  WRONG_EMAIL: ${{ secrets.WRONG_EMAIL }}
  ENVIRONMENT: production

jobs:
  setup-dependencies:
    runs-on: ubuntu-latest
    outputs:
      node-cache-key: ${{ steps.cache-node.outputs.cache-primary-key }}
      pw-cache-key: ${{ steps.cache-pw.outputs.cache-primary-key }}
    steps:
      - uses: actions/checkout@v4
      - id: cache-node
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - id: cache-pw
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
      - run: npx playwright install --with-deps
      - run: npm run lint

  tests:
    needs: setup-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [functional, accessibility, cross-browser]
        browser: [chromium, firefox, webkit]
        exclude:
          - suite: accessibility
            browser: firefox
          - suite: accessibility
            browser: webkit
          - suite: functional
            browser: firefox
          - suite: functional
            browser: webkit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ needs.setup-dependencies.outputs.node-cache-key }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ needs.setup-dependencies.outputs.pw-cache-key }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run ${{ matrix.suite }}-${{ matrix.browser }}:ci -- --workers=4
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suite }}-report-${{ matrix.browser }}
          path: playwright-report
